### PR TITLE
fixed errors when returning None refs #49

### PR DESCRIPTION
**Pull request by TalissaJoly**
issue #49

### CODE REVIEW

**Comment by koenedaele** [comment]
I'm not sure I like how what we're doing here. I'm wondering if we shouldn't be throwing something like a ValueError instead of returning None.

I'll have to think about it a bit.

**Comment by koenedaele** [comment]
I'd rather use a custom exception. Could you add a GatewayResourceNotFoundException to https://github.com/OnroerendErfgoed/crabpy/blob/master/crabpy/gateway/exception.py?

And let the methods throw this exception when something can't be found?

**Comment by koenedaele** [comment]
@TalissaJoly Is this ready for review and merge or should I wait?

**Comment by TalissaJoly** [comment]
@koenedaele I just wanted to ask what I should do with the list functions. At this moment they return an empty list. Should this be an error as well? The thing is that you can get an empty list because there are no results or because you entered a non-existing id. I don't know how we could differentiate between the two.

**Comment by koenedaele** [comment]
@TalissaJoly That sucks. Asking for the huisnummers of an unexisting street should be an error. Asking for the huisnummers of a street with no houses should be an empty list.

We could solve this by first checking if eg. the street exists, but that's an extra service call I would rather avoid. So, let's just always return empty lists.

**Comment by koenedaele** [comment]
In that case, do you still need to do something, or is this ready for review?

**Comment by TalissaJoly** [comment]
In that case it should be ready.

**Comment by koenedaele** [comment]
Could you write unit tests like the one's I've written for Gewest and Provincie?

**Pull request merged**
